# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0002_auto_20171117_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='-'),
        ),
    ]
